VoteManager/Models/Vote.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VoteManager.Models
{
    public class Vote
    {
        public int ID { get; set; }
        public int VotePhaseId { get; set; }
        public string UserName { get; set; }
        public string VoteOption { get; set; }
        public DateTime VoteDate { get; set; }
        
    }
}

VoteManager/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoteManager.DAL;
using VoteManager.ViewModel;

namespace VoteManager.Controllers
{
    public class HomeController : Controller
    {
       

        public ActionResult Index()
        {
            return View();
        }

        //[Authorize]
        //public ActionResult Results()
        //{
        //    return View(new ResultsViewModel());
        //}

        [Authorize]
        public ActionResult Vote()
        {
            ViewBag.Message = "Vote Now.";

            return View();
        }

        //[Authorize]
        //public ActionResult VoteTopics()
        //{
        //    ViewBag.Message = "Vote Topics.";

        //    return View();
        //}

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VoteManager/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoteManager.ViewModel;

namespace VoteManager.Controllers
{
    public class VoteController : Controller
    {
        private VotesViewModel viewModel;

        // GET: Vote
        [Authorize]
        public ActionResult Index()
        {
            if (viewModel == null)
                    viewModel = new VotesViewModel();
            if (!viewModel.OpenVotePhase)
                return View("Error", viewModel);
            else if (viewModel.UserVotedAlready(this.User.Identity.Name))
                return View("VotedAlready", viewModel);
            else
                return View("Index", viewModel);
        }

        public ActionResult VoteOption1(VotesViewModel viewModel)
        {
            viewModel.Vote(1, this.User.Identity.Name);
            return View("Thankyou", viewModel);

        }

        public ActionResult VoteOption2(VotesViewModel viewModel)
        {
            viewModel.Vote(2, this.User.Identity.Name);
            return View("Thankyou", viewModel);

        }
    }


}

VoteManager/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VoteManager/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VoteManager/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Vote Manager</h1>
    <p class="lead">Welcome to Vote Manager!</p>
    @Html.ActionLink("Vote Now", "Index", "Vote")
    @*<p><a href="~/Views/Home/Vote.cshtml" class="btn btn-primary btn-lg">Vote now &raquo;</a></p>*@
</div>

@*<div class="row">
    <div class="col-md-4">
        <h2>Vote Now</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

VoteManager/Views/Home/Vote.cshtml
@{
    ViewBag.Title = "Vote";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Vote</h2>